echo "=========================================="
echo "   SISTEMA DE FICHAJES LOGISTICA"
echo "=========================================="
echo ""
echo "🚀 INSTRUCCIONES PARA EJECUTAR:"
echo ""
echo "1. Abre PowerShell o CMD"
echo "2. Ejecuta estos comandos:"
echo ""
echo 'cd "C:\Users\Administrador\Desktop\app_fichajes_logistica\app_fichajes_logistica"'
echo ""
echo 'C:\Users\Administrador\Desktop\app_fichajes_logistica\.venv\Scripts\uvicorn.exe app.main:app --reload --host 127.0.0.1 --port 8000'
echo ""
echo "=========================================="
echo "🌐 Accede a la aplicación en:"
echo "   http://127.0.0.1:8000"
echo ""
echo "📋 Páginas disponibles:"
echo "   • http://127.0.0.1:8000/register"
echo "   • http://127.0.0.1:8000/login"
echo "   • http://127.0.0.1:8000/repartidor"
echo "   • http://127.0.0.1:8000/admin"
echo "=========================================="
